// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHcN-AHiG9physIKlQGBGvkhEUZn0cboY',
    appId: '1:193406993712:web:8c033bb7287a3c7a0fb4f5',
    messagingSenderId: '193406993712',
    projectId: 'caca-d4922',
    authDomain: 'caca-d4922.firebaseapp.com',
    storageBucket: 'caca-d4922.appspot.com',
    measurementId: 'G-T531YSVHXL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcQ0DJO0H3xzBvygBA42gcIZ-nAWL_XS0',
    appId: '1:193406993712:android:bb260f5dae3f07290fb4f5',
    messagingSenderId: '193406993712',
    projectId: 'caca-d4922',
    storageBucket: 'caca-d4922.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2JZOo8vhJnVqSWCoD-rt5P1v2V9kEdrc',
    appId: '1:193406993712:ios:41025f2c9f82528e0fb4f5',
    messagingSenderId: '193406993712',
    projectId: 'caca-d4922',
    storageBucket: 'caca-d4922.appspot.com',
    iosClientId: '193406993712-a9hs911udhmuhgckvoh93894b4k9h851.apps.googleusercontent.com',
    iosBundleId: 'com.dissingardjino.digitaldschool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2JZOo8vhJnVqSWCoD-rt5P1v2V9kEdrc',
    appId: '1:193406993712:ios:41025f2c9f82528e0fb4f5',
    messagingSenderId: '193406993712',
    projectId: 'caca-d4922',
    storageBucket: 'caca-d4922.appspot.com',
    iosClientId: '193406993712-a9hs911udhmuhgckvoh93894b4k9h851.apps.googleusercontent.com',
    iosBundleId: 'com.dissingardjino.digitaldschool',
  );
}
